version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: restapi_dev
    ports:
      - "5432:5432"
    volumes:
      - new_pg_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: go_api
    restart: always
    depends_on:
      - db
    environment:
      - PORT=8080
      - DATABASE_URL=host=my_postgres_container user=postgres password=password123 dbname=restapi_dev sslmode=disable
    ports:
      - "8080:8080"

volumes:
  new_pg_data:
