version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: postgres_db
      POSTGRES_PASSWORD: 123456GG
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
